swagger: "2.0"
info:
  title: "Kafka Producer API"
  description: "REST API that sends messages to Kafka"
consumes:
  - application/json
produces:
  - application/json
paths:
  /event:
    post:
      summary: "Send an event to Kafka"
      operationId: postEvent
      tags:
        - events
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/Event"
      responses:
        200:
          description: Success
definitions:
  Event:
    type: object
    required:
      - type
      - key
      - value
      - timestamp
    properties:
      type:
        type: string
      key:
        type: string
      value:
        type: string
      timestamp:
        type: integer
        format: int64
